### ISSUE TITLE
Please Merge APIs with https://github.com/socialbotspy/LinkedinPy

### ISSUE THREAD

**Issue by ishandutta2007** [manjurulhoque/python-linkedin-bot#1]
Hi Manjurul , 
You have been invited to https://github.com/socialbotspy
because of your work on this project. Please merge your APIs with https://github.com/socialbotspy/LinkedinPy
As per my understanding what I can see is clearly we can extract two APIs from here 
1) `visit_people_you_may_know()`
2) `visit_connections()`

**Comment by ishandutta2007** [comment]
@manjurulhoque  thoughts ?

**Comment by manjurulhoque** [comment]
Today will start working on it. Sorry for the delay.

**Comment by ishandutta2007** [comment]
did you work on it or couldn't install requirements ?
Actually we made it easy now, you can check.
